import type { ChainReference } from "./chains";
export type SyncDataset = "erc20" | "transactions" | "internal_native";
export interface DatasetUpdateRequest { readonly chain: ChainReference; readonly address: string; readonly dataset: SyncDataset; readonly fromBlock?: string; readonly toBlock?: string; readonly maxBlocks?: string; readonly replay?: boolean; readonly signal?: AbortSignal; }
export interface DatasetUpdateResult { readonly operation: "update" | "recollect"; readonly status: "completed" | "partial" | "busy" | "failed" | "history_replay_queued" | "history_replay_running"; readonly chainId: number; readonly address: string; readonly dataset: SyncDataset; readonly targetBlock: string; readonly requestedRange: { startBlock: string; endBlock: string }; readonly coveredRange: { startBlock: string; endBlock: string } | null; readonly nextBlock: string; readonly recordsSeen: number; readonly recordsWritten: number; readonly duplicates: number; readonly duplicateRecords: number; readonly provider: string | null; readonly runId: string; readonly replay: { requested: boolean; status: string; runId: string | null }; readonly hasNext: boolean; readonly errorCode?: string; }
export interface RecollectRequest extends DatasetUpdateRequest { readonly fromBlock: string; readonly toBlock: string; readonly strategy?: "replace" | "merge"; readonly dryRun?: boolean; readonly reason?: string; }
export interface RecollectResult extends DatasetUpdateResult { readonly operation: "recollect"; readonly strategy: "replace" | "merge"; readonly dryRun: boolean; readonly recordsDeleted: number; readonly affectedReplayFromBlock: string | null; }
export interface SyncAuditRequest { readonly chain: ChainReference; readonly address: string; readonly dataset?: SyncDataset; readonly fromBlock?: string; readonly toBlock?: string; }
export interface SyncAuditResult { readonly status: "ok" | "issues_found" | "incomplete"; readonly chainId: number; readonly address: string; readonly dataset: SyncDataset | null; readonly checkedRange: { startBlock: string; endBlock: string } | null; readonly gapRanges: readonly { startBlock: string; endBlock: string }[]; readonly duplicateCount: number; readonly cursorConsistent: boolean | null; readonly replayCoverage: { asOfBlock: string | null; revision: string | null }; readonly issues: readonly { code: string; detail: string }[]; }
export interface SyncStatus { readonly scopeKey: string; readonly chainId: number; readonly address: string; readonly dataset: SyncDataset; readonly nextBlock: string | null; readonly targetBlock: string | null; readonly lastCompleteBlock: string | null; readonly status: string; readonly updatedAt: string | null; }
