import { z } from "zod";
import { invalidRequest } from "./errors";

export interface UniswapV4HistoricalPriceRequest { readonly chain: 1 | "ethereum"; readonly blockNumber: string; readonly tokenIds?: readonly string[]; readonly tokenPair?: readonly [string, string]; readonly signal?: AbortSignal; }
export interface UniswapV4TokenPriceAtBlockRequest { readonly chain: 1 | "ethereum"; readonly blockNumber: string; readonly token: string; readonly signal?: AbortSignal; }
export interface UniswapV4TokenPricesAtBlockRequest { readonly chain: 1 | "ethereum"; readonly blockNumber: string; readonly tokens: readonly string[]; readonly signal?: AbortSignal; }
export interface UniswapV4TokenPriceAtBlockResult { readonly chainId: 1; readonly blockNumber: string; readonly blockHash: string; readonly blockTimestamp: string; readonly token: string; readonly tokenAddress: string; readonly tokenSymbol: string; readonly tokenDecimals: number; readonly priceUsd: string; readonly feeTier: number; readonly poolAddress: string; readonly quoteToken: UniswapV4Currency; readonly source: "uniswap-v4"; }
export interface UniswapV4TokenPricesAtBlockResult { readonly chainId: 1; readonly blockNumber: string; readonly blockHash: string; readonly blockTimestamp: string; readonly registryVersion: string; readonly rpcEndpointId: string; readonly executionMode: "multicall3-state-view"; readonly prices: readonly UniswapV4TokenPriceAtBlockResult[]; readonly failures: readonly { readonly token: string; readonly message: string }[]; readonly summary: { readonly requestedTokens: number; readonly succeededTokens: number; readonly failedTokens: number; readonly distinctPools: number; readonly multicallBatches: number; readonly partial: boolean; }; }
export interface UniswapV4Currency { readonly address: string; readonly kind: "native" | "erc20"; readonly symbol: string; readonly decimals: number; }
export interface UniswapV4HistoricalPrice { readonly tokenId: string; readonly tokenAddress: string; readonly tokenSymbol: string; readonly tokenDecimals: number; readonly poolId: string; readonly fee: number; readonly tickSpacing: number; readonly hooks: string; readonly currency0: UniswapV4Currency; readonly currency1: UniswapV4Currency; readonly baseCurrency: UniswapV4Currency; readonly quoteCurrency: UniswapV4Currency; readonly sqrtPriceX96: string; readonly tick: string; readonly price: string; readonly tickPrice: string; readonly ratioNumerator: string; readonly ratioDenominator: string; readonly priceUsd: string; readonly priceRounding: "floor"; readonly blockNumber: string; }
export type UniswapV4PriceFailureCode = "POOL_NOT_DEPLOYED_AT_BLOCK" | "STATE_CALL_REVERTED" | "STATE_RESPONSE_INVALID" | "POOL_KEY_INVALID" | "PRICE_CALCULATION_INVALID";
export interface UniswapV4PriceFailure { readonly tokenId: string; readonly tokenAddress: string; readonly poolId: string; readonly code: UniswapV4PriceFailureCode; readonly retryable: false; readonly message: string; }
export interface UniswapV4HistoricalPriceResult { readonly chainId: 1; readonly blockNumber: string; readonly blockHash: string; readonly blockTimestamp: string; readonly registryVersion: string; readonly rpcEndpointId: string; readonly executionMode: "multicall3-state-view"; readonly stateSource: "state-view"; readonly priceScale: 18; readonly prices: readonly UniswapV4HistoricalPrice[]; readonly failures: readonly UniswapV4PriceFailure[]; readonly summary: { readonly configuredPools: number; readonly requestedTokens: number; readonly succeededTokens: number; readonly failedTokens: number; readonly distinctPools: number; readonly multicallBatches: number; readonly partial: boolean; }; }
const base = z.object({ chain: z.union([z.literal(1), z.literal("ethereum")]), blockNumber: z.string().max(78).regex(/^\d+$/), signal: z.custom<AbortSignal>((v) => v instanceof AbortSignal).optional() }).strict();
export function parseUniswapV4HistoricalPriceRequest(input: unknown): UniswapV4HistoricalPriceRequest { const p = base.extend({ tokenIds: z.array(z.string().trim().min(1)).min(1).optional(), tokenPair: z.tuple([z.string().trim().min(1), z.string().trim().min(1)]).optional() }).safeParse(input); if (!p.success || (p.data.tokenIds && p.data.tokenPair) || (p.data.tokenIds && new Set(p.data.tokenIds.map((x) => x.toLowerCase())).size !== p.data.tokenIds.length) || (p.data.tokenPair && p.data.tokenPair[0].toLowerCase() === p.data.tokenPair[1].toLowerCase())) throw invalidRequest("Invalid Uniswap V4 historical price request."); return Object.freeze({ chain: p.data.chain, blockNumber: p.data.blockNumber.replace(/^0+(?=\d)/, "") || "0", ...(p.data.tokenIds ? { tokenIds: Object.freeze(p.data.tokenIds) } : {}), ...(p.data.tokenPair ? { tokenPair: Object.freeze(p.data.tokenPair) } : {}), ...(p.data.signal ? { signal: p.data.signal } : {}) }); }
export function parseUniswapV4TokenPriceAtBlockRequest(input: unknown): UniswapV4TokenPriceAtBlockRequest { const p = base.extend({ token: z.string().trim().min(1) }).safeParse(input); if (!p.success) throw invalidRequest("Invalid Uniswap V4 token USD price request."); return Object.freeze({ chain: p.data.chain, token: p.data.token, blockNumber: p.data.blockNumber.replace(/^0+(?=\d)/, "") || "0", ...(p.data.signal ? { signal: p.data.signal } : {}) }); }
export function parseUniswapV4TokenPricesAtBlockRequest(input: unknown): UniswapV4TokenPricesAtBlockRequest { const p = base.extend({ tokens: z.array(z.string().trim().min(1)).min(1) }).safeParse(input); if (!p.success || new Set(p.data.tokens.map((x) => x.toLowerCase())).size !== p.data.tokens.length) throw invalidRequest("Invalid Uniswap V4 token USD price request."); return Object.freeze({ chain: p.data.chain, blockNumber: p.data.blockNumber.replace(/^0+(?=\d)/, "") || "0", tokens: Object.freeze(p.data.tokens), ...(p.data.signal ? { signal: p.data.signal } : {}) }); }
