/**
 * GENERATED FILE — do not edit by hand.
 *
 * Produced by `scripts/update-chainlink-ethereum-feeds.mjs`. Regenerate with:
 *
 *   pnpm update:chainlink-feeds
 *
 * See `docs/CHAINLINK_ETHEREUM_ARCHIVE_RPC_MULTICALL3_UPGRADE.md` section 6 and
 * `docs/CHAINLINK_ETHEREUM_ARCHIVE_RPC_MAINTENANCE.md` section 7 before editing the
 * generator or committing a refreshed manifest. Review added, removed,
 * changed-address, changed-decimals, changed-heartbeat, SVR, and deprecating
 * entries against Chainlink's official address page before committing.
 *
 * Source: https://reference-data-directory.vercel.app/feeds-mainnet.json
 * Retrieved: 2026-08-07T00:00:00.000Z
 * Source SHA-256: bf7d6f90360ab0e8eec597668506119f273cc02551298ab01acb771c42c6e6ae
 * Feed count: 71
 */

import type { ChainlinkFeedDefinition } from "./ChainlinkFeedDefinition";

export const ETHEREUM_MAINNET_CHAINLINK_PRICE_FEEDS: readonly ChainlinkFeedDefinition[] = Object.freeze([
  Object.freeze({
    id: "ethereum-mainnet:1inch-usd",
    chainId: 1,
    proxyAddress: "0xc929ad75B72593967DE83E7F7Cda0493458261D9",
    assetSymbol: "1INCH",
    assetName: "1inch",
    baseAsset: "1INCH",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "1inch-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:aave-usd",
    chainId: 1,
    proxyAddress: "0x547a514d5e3769680Ce22B2361c10Ea13619e8a9",
    assetSymbol: "AAVE",
    assetName: "Aave",
    baseAsset: "AAVE",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "3600",
    sourcePath: "aave-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:arb-usd",
    chainId: 1,
    proxyAddress: "0x31697852a68433DbCc2Ff612c516d69E3D9bd08F",
    assetSymbol: "ARB",
    assetName: "Arbitrum",
    baseAsset: "ARB",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "arb-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:ausd-usd",
    chainId: 1,
    proxyAddress: "0xB00341502DfEA6Ced8A5786b4059d29dA5E4D1FD",
    assetSymbol: "AUSD",
    assetName: "AUSD",
    baseAsset: "AUSD",
    quoteAsset: "USD",
    expectedDecimals: 18,
    heartbeatSeconds: "86400",
    sourcePath: "ausd-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:avax-usd",
    chainId: 1,
    proxyAddress: "0xFF3EEb22B5E3dE6e705b44749C2559d704923FD7",
    assetSymbol: "AVAX",
    assetName: "Avalanche",
    baseAsset: "AVAX",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "avax-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:bal-usd",
    chainId: 1,
    proxyAddress: "0xdF2917806E30300537aEB49A7663062F4d1F2b5F",
    assetSymbol: "BAL",
    assetName: "Balancer",
    baseAsset: "BAL",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "bal-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:bnb-usd",
    chainId: 1,
    proxyAddress: "0x14e613AC84a31f709eadbdF89C6CC390fDc9540A",
    assetSymbol: "BNB",
    assetName: "BNB",
    baseAsset: "BNB",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "bnb-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:btc-usd",
    chainId: 1,
    proxyAddress: "0xF4030086522a5bEEa4988F8cA5B36dbC97BeE88c",
    assetSymbol: "BTC",
    assetName: "Bitcoin",
    baseAsset: "BTC",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "3600",
    sourcePath: "btc-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:cbbtc-usd",
    chainId: 1,
    proxyAddress: "0x2665701293fCbEB223D11A08D826563EDcCE423A",
    assetSymbol: "cbBTC",
    assetName: "Coinbase Wrapped Bitcoin",
    baseAsset: "CBBTC",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "cbbtc-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:comp-usd",
    chainId: 1,
    proxyAddress: "0xdbd020CAeF83eFd542f4De03e3cF0C28A4428bd5",
    assetSymbol: "COMP",
    assetName: "Compound",
    baseAsset: "COMP",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "3600",
    sourcePath: "comp-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:crv-usd",
    chainId: 1,
    proxyAddress: "0xCd627aA160A6fA45Eb793D19Ef54f5062F20f33f",
    assetSymbol: "CRV",
    assetName: "Curve DAO",
    baseAsset: "CRV",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "crv-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:crvusd-usd",
    chainId: 1,
    proxyAddress: "0xEEf0C605546958c1f899b6fB336C20671f9cD49F",
    assetSymbol: "CRVUSD",
    assetName: "crvUSD",
    baseAsset: "CRVUSD",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "crvusd-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:cvx-usd",
    chainId: 1,
    proxyAddress: "0xd962fC30A72A84cE50161031391756Bf2876Af5D",
    assetSymbol: "CVX",
    assetName: "Convex Finance",
    baseAsset: "CVX",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "cvx-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:dai-usd",
    chainId: 1,
    proxyAddress: "0xAed0c38402a5d19df6E4c03F4E2DceD6e29c1ee9",
    assetSymbol: "DAI",
    assetName: "DAI",
    baseAsset: "DAI",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "3600",
    sourcePath: "dai-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:dola-usd",
    chainId: 1,
    proxyAddress: "0xE33592594f72Cc7ec8a05788be8E8455746C3a32",
    assetSymbol: "DOLA",
    assetName: "DOLA",
    baseAsset: "DOLA",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "dola-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:eigen-usd",
    chainId: 1,
    proxyAddress: "0xf2917e602C2dCa458937fad715bb1E465305A4A1",
    assetSymbol: "EIGEN",
    assetName: "Eigenlayer",
    baseAsset: "EIGEN",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "eigen-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:ens-usd",
    chainId: 1,
    proxyAddress: "0x5C00128d4d1c2F4f652C267d7bcdD7aC99C16E16",
    assetSymbol: "ENS",
    assetName: "Ethereum Name Service",
    baseAsset: "ENS",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "ens-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:eth-usd",
    chainId: 1,
    proxyAddress: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419",
    assetSymbol: "ETH",
    assetName: "Ethereum",
    baseAsset: "ETH",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "3600",
    sourcePath: "eth-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:eurc-usd",
    chainId: 1,
    proxyAddress: "0x04F84020Fdf10d9ee64D1dcC2986EDF2F556DA11",
    assetSymbol: "EURC",
    assetName: "Circle EUR",
    baseAsset: "EURC",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "eurc-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:fdusd-usd",
    chainId: 1,
    proxyAddress: "0xfAA9147190c2C2cc5B8387B4f49016bDB3380572",
    assetSymbol: "FDUSD",
    assetName: "First Digital USD",
    baseAsset: "FDUSD",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "fdusd-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:frax-usd",
    chainId: 1,
    proxyAddress: "0xB9E1E3A9feFf48998E45Fa90847ed4D467E8BcfD",
    assetSymbol: "FRAX",
    assetName: "Legacy Frax",
    baseAsset: "FRAX.OLD",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "3600",
    sourcePath: "frax-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:frxusd-usd",
    chainId: 1,
    proxyAddress: "0x9B4a96210bc8D9D55b1908B465D8B0de68B7fF83",
    assetSymbol: "frxUSD",
    assetName: "Frax USD",
    baseAsset: "FRXUSD",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "frxusd-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:fxs-usd",
    chainId: 1,
    proxyAddress: "0x6Ebc52C8C1089be9eB3945C4350B68B8E4C2233f",
    assetSymbol: "FXS",
    assetName: "FRAX",
    baseAsset: "FRAX",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "fxs-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:gho-usd",
    chainId: 1,
    proxyAddress: "0x3f12643D3f6f874d39C2a4c9f2Cd6f2DbAC877FC",
    assetSymbol: "GHO",
    assetName: "GHO",
    baseAsset: "GHO",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "gho-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:grt-usd",
    chainId: 1,
    proxyAddress: "0x86cF33a451dE9dc61a2862FD94FF4ad4Bd65A5d2",
    assetSymbol: "GRT",
    assetName: "The Graph",
    baseAsset: "GRT",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "grt-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:imx-usd",
    chainId: 1,
    proxyAddress: "0xBAEbEFc1D023c0feCcc047Bff42E75F15Ff213E6",
    assetSymbol: "IMX",
    assetName: "Immutable X",
    baseAsset: "IMX",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "imx-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:knc-usd",
    chainId: 1,
    proxyAddress: "0xf8fF43E991A81e6eC886a3D281A2C6cC19aE70Fc",
    assetSymbol: "KNC",
    assetName: "Kyber Network",
    baseAsset: "KNC",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "knc-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:link-usd",
    chainId: 1,
    proxyAddress: "0x2c1d072e956AFFC0D435Cb7AC38EF18d24d9127c",
    assetSymbol: "LINK",
    assetName: "Chainlink",
    baseAsset: "LINK",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "3600",
    sourcePath: "link-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:lusd-usd",
    chainId: 1,
    proxyAddress: "0x3D7aE7E594f2f2091Ad8798313450130d0Aba3a0",
    assetSymbol: "LUSD",
    assetName: "Liquity USD",
    baseAsset: "LUSD",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "lusd-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:mavia-usd",
    chainId: 1,
    proxyAddress: "0x29d26C008e8f201eD0D864b1Fd9392D29d0C8e96",
    assetSymbol: "MAVIA",
    assetName: "Heroes of Mavia",
    baseAsset: "MAVIA",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "mavia-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:mkr-usd",
    chainId: 1,
    proxyAddress: "0xec1D1B3b0443256cc3860e24a46F108e699484Aa",
    assetSymbol: "MKR",
    assetName: "Maker",
    baseAsset: "MKR",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "3600",
    sourcePath: "mkr-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:musd-usd",
    chainId: 1,
    proxyAddress: "0xc90E3460424fb8ea79775089E9053113FEE34Ed0",
    assetSymbol: "MUSD",
    assetName: "MetaMask USD",
    baseAsset: "MUSD",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "musd-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:paxg-usd",
    chainId: 1,
    proxyAddress: "0x9944D86CEB9160aF5C5feB251FD671923323f8C3",
    assetSymbol: "PAXG",
    assetName: "Pax Gold",
    baseAsset: "PAXG",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "paxg-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:pyusd-usd",
    chainId: 1,
    proxyAddress: "0x8f1dF6D7F2db73eECE86a18b4381F4707b918FB1",
    assetSymbol: "PYUSD",
    assetName: "PayPal USD",
    baseAsset: "PYUSD",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "pyusd-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:rdnt-usd",
    chainId: 1,
    proxyAddress: "0x393CC05baD439c9B36489384F11487d9C8410471",
    assetSymbol: "RDNT",
    assetName: "Radiant Capital",
    baseAsset: "RDNT",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "rdnt-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:rlusd-usd",
    chainId: 1,
    proxyAddress: "0x26C46B7aD0012cA71F2298ada567dC9Af14E7f2A",
    assetSymbol: "RLUSD",
    assetName: "Ripple USD",
    baseAsset: "RLUSD",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "rlusd-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:rpl-usd",
    chainId: 1,
    proxyAddress: "0x4E155eD98aFE9034b7A5962f6C84c86d869daA9d",
    assetSymbol: "RPL",
    assetName: "Rocket Pool",
    baseAsset: "RPL",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "rpl-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:rsr-usd",
    chainId: 1,
    proxyAddress: "0x759bBC1be8F90eE6457C44abc7d443842a976d02",
    assetSymbol: "RSR",
    assetName: "Reserve Rights",
    baseAsset: "RSR",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "rsr-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:sand-usd",
    chainId: 1,
    proxyAddress: "0x35E3f7E558C04cE7eEE1629258EcbbA03B36Ec56",
    assetSymbol: "SAND",
    assetName: "The Sandbox",
    baseAsset: "SAND",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "sand-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:sky-usd",
    chainId: 1,
    proxyAddress: "0xee10fE5E7aa92dd7b136597449c3d5813cFC5F18",
    assetSymbol: "SKY",
    assetName: "Sky",
    baseAsset: "SKY",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "sky-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:snx-usd",
    chainId: 1,
    proxyAddress: "0xDC3EA94CD0AC27d9A86C180091e7f78C683d3699",
    assetSymbol: "SNX",
    assetName: "Synthetix Network",
    baseAsset: "SNX",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "snx-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:sol-usd",
    chainId: 1,
    proxyAddress: "0x4ffC43a60e009B551865A93d232E33Fce9f01507",
    assetSymbol: "SOL",
    assetName: "Solana",
    baseAsset: "SOL",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "sol-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:spell-usd",
    chainId: 1,
    proxyAddress: "0x8c110B94C5f1d347fAcF5E1E938AB2db60E3c9a8",
    assetSymbol: "SPELL",
    assetName: "Spell Token",
    baseAsset: "SPELL",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "spell-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:steth-usd",
    chainId: 1,
    proxyAddress: "0xCfE54B5cD566aB89272946F602D76Ea879CAb4a8",
    assetSymbol: "STETH",
    assetName: "Lido Staked ETH",
    baseAsset: "STETH",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "3600",
    sourcePath: "steth-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:stg-usd",
    chainId: 1,
    proxyAddress: "0x7A9f34a0Aa917D438e9b6E630067062B7F8f6f3d",
    assetSymbol: "STG",
    assetName: "Stargate Finance",
    baseAsset: "STG",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "stg-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:susde-usd",
    chainId: 1,
    proxyAddress: "0xFF3BC18cCBd5999CE63E788A1c250a88626aD099",
    assetSymbol: "sUSDe",
    assetName: "Ethena Staked USDe",
    baseAsset: "SUSDE",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "susde-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:sushi-usd",
    chainId: 1,
    proxyAddress: "0xCc70F09A6CC17553b2E31954cD36E4A2d89501f7",
    assetSymbol: "SUSHI",
    assetName: "Sushi",
    baseAsset: "SUSHI",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "sushi-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:sxt-usd",
    chainId: 1,
    proxyAddress: "0x2D27d9e1b74936D8E83c4BA118F09A4c4a897f62",
    assetSymbol: "SXT",
    assetName: "Space and Time",
    baseAsset: "SXT",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "sxt-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:tao-usd",
    chainId: 1,
    proxyAddress: "0x1c88503c9A52aE6aaE1f9bb99b3b7e9b8Ab35459",
    assetSymbol: "TAO",
    assetName: "Bittensor",
    baseAsset: "TAO",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "tao-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:tbtc-usd",
    chainId: 1,
    proxyAddress: "0x8350b7De6a6a2C1368E7D4Bd968190e13E354297",
    assetSymbol: "TBTC",
    assetName: "tBTC",
    baseAsset: "tBTC",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "tbtc-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:trump-usd",
    chainId: 1,
    proxyAddress: "0x7f0347903F413a6C4c540f39145E2a2249639931",
    assetSymbol: "TRUMP",
    assetName: "Official Trump",
    baseAsset: "TRUMP",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "trump-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:tusd-usd",
    chainId: 1,
    proxyAddress: "0xec746eCF986E2927Abd291a2A1716c940100f8Ba",
    assetSymbol: "TUSD",
    assetName: "True USD",
    baseAsset: "TUSD",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "tusd-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:u-usd",
    chainId: 1,
    proxyAddress: "0xF6351B2dCF0110E76c71C1d319Af2f410454B6f3",
    assetSymbol: "U",
    assetName: "United Stables",
    baseAsset: "U",
    quoteAsset: "USD",
    expectedDecimals: 18,
    heartbeatSeconds: "86400",
    sourcePath: "u-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:uni-usd",
    chainId: 1,
    proxyAddress: "0x553303d460EE0afB37EdFf9bE42922D8FF63220e",
    assetSymbol: "UNI",
    assetName: "Uniswap",
    baseAsset: "UNI",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "3600",
    sourcePath: "uni-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:usd0++-usd",
    chainId: 1,
    proxyAddress: "0xFC9e30Cf89f8A00dba3D34edf8b65BCDAdeCC1cB",
    assetSymbol: "USD0++",
    assetName: "Staked USD0",
    baseAsset: "USD0++",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "usd0++-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:usd0-usd",
    chainId: 1,
    proxyAddress: "0x7e891DEbD8FA0A4Cf6BE58Ddff5a8ca174FebDCB",
    assetSymbol: "USD0",
    assetName: "Usual USD",
    baseAsset: "USD0",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "usd0-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:usd1-usd",
    chainId: 1,
    proxyAddress: "0xF0d9bb015Cd7BfAb877B7156146dc09Bf461370d",
    assetSymbol: "USD1",
    assetName: "World Liberty Financial USD",
    baseAsset: "USD1",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "usd1-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:usdc-usd",
    chainId: 1,
    proxyAddress: "0x8fFfFfd4AfB6115b954Bd326cbe7B4BA576818f6",
    assetSymbol: "USDC",
    assetName: "Circle USD",
    baseAsset: "USDC",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "82800",
    sourcePath: "usdc-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:usde-usd",
    chainId: 1,
    proxyAddress: "0xa569d910839Ae8865Da8F8e70FfFb0cBA869F961",
    assetSymbol: "USDe",
    assetName: "Ethena USDe",
    baseAsset: "USDE",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "82800",
    sourcePath: "usde-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:usdf-usd",
    chainId: 1,
    proxyAddress: "0xb177857a1799aA5F7fEb5799Fdf12CbE8fdF78B1",
    assetSymbol: "USDf",
    assetName: "Falcon USD",
    baseAsset: "USDf",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "usdf-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:usdg-usd",
    chainId: 1,
    proxyAddress: "0x14f0737d6b705259e521EA6E9E3506AC78dBd311",
    assetSymbol: "USDG",
    assetName: "Global Dollar",
    baseAsset: "USDG",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "usdg-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:usdp-usd",
    chainId: 1,
    proxyAddress: "0x09023c0DA49Aaf8fc3fA3ADF34C6A7016D38D5e3",
    assetSymbol: "USDP",
    assetName: "Pax Dollar",
    baseAsset: "USDP",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "usdp-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:usds-usd",
    chainId: 1,
    proxyAddress: "0xfF30586cD0F29eD462364C7e81375FC0C71219b1",
    assetSymbol: "USDS",
    assetName: "USDS",
    baseAsset: "USDS",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "82800",
    sourcePath: "usds-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:usdt-usd",
    chainId: 1,
    proxyAddress: "0x3E7d1eAB13ad0104d2750B8863b489D65364e32D",
    assetSymbol: "USDT",
    assetName: "Tether USD",
    baseAsset: "USDT",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "usdt-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:usdtb-usd",
    chainId: 1,
    proxyAddress: "0x66704DAD467A7cA508B3be15865D9B9F3E186c90",
    assetSymbol: "USDtb",
    assetName: "Ethena USDtb",
    baseAsset: "USDtb",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "usdtb-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:usr-usd",
    chainId: 1,
    proxyAddress: "0x34ad75691e25A8E9b681AAA85dbeB7ef6561B42c",
    assetSymbol: "USR",
    assetName: "Resolv USR",
    baseAsset: "USR",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "usr-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:wlfi-usd",
    chainId: 1,
    proxyAddress: "0x14E5FC91Ddb3f97C33013Cc9fA74F54062Ad1Aa1",
    assetSymbol: "WLFI",
    assetName: "World Liberty Financial",
    baseAsset: "WLFI",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "wlfi-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:xcn-usd",
    chainId: 1,
    proxyAddress: "0xeb988B77b94C186053282BfcD8B7ED55142D3cAB",
    assetSymbol: "XCN",
    assetName: "Chain",
    baseAsset: "XCN",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "xcn-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:yfi-usd",
    chainId: 1,
    proxyAddress: "0xA027702dbb89fbd58938e4324ac03B58d812b0E1",
    assetSymbol: "YFI",
    assetName: "Yearn Finance",
    baseAsset: "YFI",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "yfi-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:zec-usd",
    chainId: 1,
    proxyAddress: "0x3f929667bdf783b99274F10465a89d6aF772736E",
    assetSymbol: "ZEC",
    assetName: "Zcash",
    baseAsset: "ZEC",
    quoteAsset: "USD",
    expectedDecimals: 18,
    heartbeatSeconds: "86400",
    sourcePath: "zec-usd",
  }),
  Object.freeze({
    id: "ethereum-mainnet:zrx-usd",
    chainId: 1,
    proxyAddress: "0x2885d15b8Af22648b98B122b22FDF4D2a56c6023",
    assetSymbol: "ZRX",
    assetName: "0x",
    baseAsset: "ZRX",
    quoteAsset: "USD",
    expectedDecimals: 8,
    heartbeatSeconds: "86400",
    sourcePath: "zrx-usd",
  }),
]);
